test:
  xmake && xmake r tests

t2:
  xmake && xmake r t2 < HW04/t2.in > HW04/t2.out

t1:
  g++ -std=c++17 -o2 HW04/t1.cpp -o HW04/t1 \
    && ./HW04/t1 < HW04/t1.in > HW04/t1.out \
    && rm HW04/t1
