default:
  @just --list

dev:
  xmake && xmake r

valgrind:
  xmake f --toolchain=gcc -m valgrind
  xmake
  valgrind --tool=memcheck ./build/linux/x86_64/valgrind/lab2 -s

linux:
  xmake f --toolchain=gcc -p linux -m release
