== Introduction

== Experimental methods

=== Small-angle X-ray scattering (SAXS) and data analysis

SAXS measurements were conducted at Shanghai Synchrotron Radiation Facility (SSRF) with 12keV X-ray beam at a sample-to-detector distance of 2.6418877683350463m (calculated by pyFAI).

The scattering vector q is defined as q = 4πsinθ/λ, where 2θ is the scattering angle and λ is the X-ray wavelength. The sample-to-detector distance was 2.5 m, covering a q range of 0.01–0.5 Å^−1. The scattering intensity I(q) was recorded as a function of q. The data were processed using the ATSAS package (Petoukhov et al., 2012). The radius of gyration (R_g) was calculated using the Guinier approximation (Guinier, 1939). The pair distance distribution function P(r) was calculated using the program GNOM (Svergun, 1992). The maximum particle dimension D_max was estimated from the P(r) function. The ab initio shape reconstruction was performed using the program DAMMIF (Franke and Svergun, 2009). The final model was generated by averaging 20 independent DAMMIF models using the program DAMAVER (Volkov and Svergun, 2003). Theoretical scattering curves were calculated from the atomic coordinates using the program CRYSOL (Svergun et al., 1995). The fitting of the experimental data was performed using the program PRIMUS (Konarev et al., 2003).
