[project]
name = "bayes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "pgmpy>=1.0.0",
    "pygraphviz>=1.14",
    "pyparsing>=3.2.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
