default:
  @just --list

dev:
  xmake && xmake run

debug:
  xmake f -m debug && xmake

py:
  python src/__init__.py

doc:
  typst c report.typ

zip: doc
  xmake
  node zip.mjs

clean:
  xmake clean --all # clean cpp build cache
  rm report.pdf # clean pdf

all:
  just zip
  just clean
